### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by adamkdean** [edge/monitor#1]
The network monitoring tool, `edge/monitor`, needs to be able to monitor the performance of the network. It should take in a configuration as an environment variable in yaml (see example below). It should perform a number of requests and record the response times, these include DNS, TCP, SSL (connection setup) timings, along with the TTFB and the download timings. _It's important to note that the TTFB should not include the connection setup._

The tool should expose these statistics on a `/metrics` path for Prometheus to pick up. The metrics should use the target name as a label so that they can be filtered properly in Grafana. I'd also recommend offsetting the requests or performing them synchronously to avoid any side effects impacting measurement.

Finally, there should be an env var for the metrics token, and an env var for the frequency (default to 15000 ms)

```yaml
targets:
  - name: 'uncached_image'
    url: 'https://monitor.test.network/images/uncached.png'
  - name: 'cached_image'
    url: 'https://monitor.test.network/images/cached.png'
  - name: 'uncached_asset'
    url: 'https://monitor.test.network/assets/uncached.txt'
  - name: 'cached_asset'
    url: 'https://monitor.test.network/assets/cached.txt'
```
